# Generated by Django 2.1.5 on 2019-05-14 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sleep', models.DurationField(default=datetime.timedelta(0, 28800))),
                ('sleep_quality', models.CharField(max_length=15)),
                ('fatigue', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('motivation', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('type', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='KG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RestingHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RMSSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SDNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='Run', max_length=15)),
                ('activity_type', models.CharField(default='Road', max_length=15)),
                ('duration', models.DurationField()),
                ('rpe', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('tss', models.DecimalField(decimal_places=1, default=50.0, max_digits=5)),
                ('tss_method', models.CharField(default='RPE', max_length=15)),
                ('km', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('kj', models.IntegerField(default=0.0)),
                ('ascent_metres', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0, null=True)),
                ('is_race', models.BooleanField(default=False)),
                ('cadence', models.IntegerField(blank=True, null=True)),
                ('watts', models.IntegerField(blank=True, null=True)),
                ('watts_estimated', models.BooleanField(default=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('is_brick', models.BooleanField(default=False)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutentry.Day')),
            ],
        ),
    ]
