# Generated by Django 2.1.5 on 2019-05-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=15)),
                ('activity_type', models.CharField(max_length=15)),
                ('duration', models.DurationField()),
                ('rpe', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tss', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tss_method', models.CharField(max_length=15)),
                ('km', models.DecimalField(decimal_places=1, max_digits=5)),
                ('kj', models.IntegerField()),
                ('ascent_metres', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('keywords', models.TextField()),
                ('is_race', models.BooleanField()),
                ('cadence', models.IntegerField()),
                ('watts', models.IntegerField()),
                ('watts_estimated', models.BooleanField()),
                ('heart_rate', models.IntegerField()),
                ('is_brick', models.BooleanField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
